### ISSUE TITLE
Connection between Equipment Items and Tiers

### ISSUE THREAD

**Issue by JavieraStephanie** [NinjaVault/NinjaHive#30]
I don't really get how the tiers and equipment items connect to each other. So, we know that a weapon have tiers. For example, a **Golden Pendant** will become a **Ruby Pendant** after reaching certain level. But even so, each tier will have different values, description, etc (the info). When I created the pendant, I could only enter the info for one pendant (basically one tier)

**Comment by QuantumHive** [comment]
Redesigned in v0.3.1
See https://github.com/NinjaVault/NinjaHive/commit/5a73f3436ebe26b37af35d36bbc144f58187b6c2
